name:
  stripeshop

services:
  api:
    image: $DOCKER_USERNAME/stripeshop-api
    restart: on-failure
    volumes:
      - stripes:/app/stripes
      - db:/app/db
      - zips:/app/zips
    ports:
      - $API_HOST_PORT:$API_PORT
    env_file:
      - prod.env
    hostname: $API_HOST
    command: bash -c 'bash scripts/setup-prod.sh && node server.js'

  app:
    image: $DOCKER_USERNAME/stripeshop-app
    restart: on-failure
    depends_on:
      api:
        condition: service_started
    volumes:
      - stripes:/usr/share/nginx/html/stripes
    ports:
      - $APP_HOST_PORT:$APP_PORT
    env_file:
      - prod.env
    hostname: $APP_HOST

volumes:
  db:
  zips:
  stripes: