services:
  base:
    build:
      context: .
      target: base
      args:
        - USERID=$USERID
    environment:
      # forward from the environment. That's kinda ugly, but we need
      # them here as well as in the services below
      - NODE_ENV
      - SMTP_SERVER
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASSWORD
      - SMTP_FROM
      - API_HOST
      - API_PORT
      - APP_HOST
      - APP_PORT
      - STATIC_SERVER
      - STATIC_PATH
      - DB_FILE
      - BASE_URL
    volumes:
      - .:/app
      - ./db:/db
    working_dir: /app
    command: ./scripts/setup_dev.sh

  api:
    depends_on:
      base:
        condition: service_completed_successfully
    extends:
      service: base
    ports:
      # this is where we're listening for browser connections
      - $API_PORT:$API_PORT
    user: node
    hostname: $API_HOST
    command: npm run api

  app:
    depends_on:
      base:
        condition: service_completed_successfully
    extends:
      service: base
    ports:
      # exposed for vite to be able to open a websocket there (HMR, yay!)
      - $APP_PORT:$APP_PORT
    user: node
    hostname: $APP_HOST
    # --host option is needed here because otherwise vite listens only on
    #   localhost, and localhost here refers to the container, thus making it
    #   unreachable from the host
    command: npx vite --host

