name:
  stripeshop

services:
  stripeshop:
    image: kotomka/stripeshop
    restart: on-failure
    env_file:
      - prod.env
    volumes:
      - db:/db
      - zips:/app/zips
    network_mode: "host"
    ports:
      - 127.0.0.1:3002:3002
    # networks:
      # stripeshop: {}
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    command:
      node server.js

volumes:
  db:
  zips: