name:
  stripeshop

services:
  stripeshop:
    image: kotomka/stripeshop
    restart: on-failure
    environment:
      - STATIC_SERVER=express
      - NODE_ENV=production
    volumes:
      - db:/db
    # networks:
    #   - stripeshop
    ports:
      - 127.0.0.1:3002:3002
    command:
      node server.js

volumes:
  db:
#     external: true