services:
  base:
    image: node
    volumes:
      - .:/app
      - ./db:/db
    environment:
      - NODE_ENV=dev

      - API_HOST=api
      - API_PORT=3002

      - APP_HOST=app
      - APP_PORT=3000

      - DB_FILE=/db/stripeshop.db

    working_dir: /app
    command: ./scripts/setup_dev.sh

  app:
    depends_on:
      base:
        condition: service_completed_successfully
    extends:
      service: base
    ports:
      # exposed for vite to be able to open a websocket there
      - 3000:3000
    command: npx vite --host

  api:
    depends_on:
      base:
        condition: service_completed_successfully
    extends:
      service: base
    ports:
      - 3002:3002
    command: npm run api
